"use client";

import { useLanguage } from "./language";
import { useState } from "react";
import type { ArchitectureNode } from "./architecture-model";

export function JsonEditor({label, value, onChange}: {label: string; value: unknown; onChange: (value: Record<string, unknown>) => void}) {
  const { t } = useLanguage();
  const [text, setText] = useState(JSON.stringify(value ?? {}, null, 2));
  const [error, setError] = useState("");
  return <label>{t(label)}<textarea value={text} spellCheck={false} onChange={e => {setText(e.target.value); try {const next = JSON.parse(e.target.value); if (!next || typeof next !== "object" || Array.isArray(next)) throw new Error("Use a JSON object"); setError(""); onChange(next);} catch (err) {setError(err instanceof Error ? err.message : "Invalid JSON");}}} />{error && <small role="alert">{t(error)}{t(". The draft keeps the last valid JSON until this is corrected.")}</small>}</label>;
}

export function RuntimeEditor({node, nodes = [], update}: {node: ArchitectureNode; nodes?: ArchitectureNode[]; update: (patch: Partial<ArchitectureNode>) => void}) {
  const { t } = useLanguage();
  const config = (node.annotations?.["interlock.runtime"] ?? {}) as Record<string, unknown>;
  const kind = String(config.kind ?? "");
  function patch(value: Record<string, unknown>) {update({annotations: {...node.annotations, "interlock.runtime": {...config, ...value}}});}
  const isAgent = node.type === "AGENT" || node.type === "SUBAGENT";
  return <section className="runtime-editor"><h4>{t("Runtime behavior")}</h4>
    {(isAgent || node.type === "TOOL") && <><label>{t("Implementation")}<select value={kind} onChange={e => {const kind = e.target.value; const annotations = {...node.annotations}; if (!kind) delete annotations["interlock.runtime"]; else annotations["interlock.runtime"] = kind === "ANTHROPIC" ? {kind, model: "", systemPrompt: "", maxTokens: 1024, maxSteps: 5, credentialRef: "", providerActorId: "", purpose: "MODEL_INFERENCE", dataClasses: ["D2"]} : kind === "HTTP_JSON" ? {kind, endpoint: "", method: "GET", purpose: "PROCESS", dataClasses: ["D3"]} : {kind, template: {message: {$path: "arguments.message"}}, purpose: "PROCESS", dataClasses: ["D3"]}; update({annotations,...(kind === "JSON_TRANSFORM" || kind === "HTTP_JSON" ? {sideEffects:["READ"]} : {})});}}><option value="">{isAgent ? t("Deterministic task dispatch") : t("Host adapter (requires binding)")}</option>{isAgent ? <option>ANTHROPIC</option> : <><option>JSON_TRANSFORM</option><option>HTTP_JSON</option></>}</select></label>
    {kind && <><label>{t("Purpose")}<input value={String(config.purpose ?? "")} onChange={e => patch({purpose:e.target.value})}/></label><label>{t("Data classes")}<input value={(Array.isArray(config.dataClasses) ? config.dataClasses : []).join(", ")} onChange={e => patch({dataClasses: e.target.value.split(",").map(s => s.trim()).filter(Boolean)})}/></label></>}
    {kind === "JSON_TRANSFORM" && <JsonEditor key={`${node.id}-${kind}`} label={t("Output template · use {$path: arguments.message}")} value={config.template} onChange={template => patch({template})}/>}
    {kind === "HTTP_JSON" && <><label>{t("Fixed HTTPS endpoint")}<input type="url" value={String(config.endpoint ?? "")} onChange={e => patch({endpoint:e.target.value})}/></label><label>{t("HTTP method")}<select value={String(config.method ?? "GET")} onChange={e => update({annotations:{...node.annotations,"interlock.runtime":{...config,method:e.target.value}},sideEffects:[e.target.value === "GET" ? "READ" : "EXTERNAL_WRITE"]})}><option>GET</option><option>POST</option></select></label><p className="field-help">{t("Declare this host in Allowed domains and its side effects below. Host preflight checks the binding.")}</p></>}
    {(kind === "HTTP_JSON" || kind === "ANTHROPIC") && <label>{t("Host credential reference")}{kind === "HTTP_JSON" ? t(" (optional)") : ""}<input value={String(config.credentialRef ?? "")} onChange={e => patch({credentialRef:e.target.value || undefined})}/><small>{t("Use a catalog name from Deploy → Host readiness. Never paste a secret.")}</small></label>}
    {kind === "ANTHROPIC" && <><label>{t("Model")}<input value={String(config.model ?? "")} onChange={e => patch({model:e.target.value})}/></label><label>{t("System prompt")}<textarea value={String(config.systemPrompt ?? "")} onChange={e => patch({systemPrompt:e.target.value})}/></label><label>{t("Provider actor ID")}<input value={String(config.providerActorId ?? "")} onChange={e => patch({providerActorId:e.target.value})}/></label><p className="field-help">{t("Add an EXTERNAL provider actor allowing api.anthropic.com, with a REL-07 MODEL_INFERENCE policy from this agent.")}</p><label>{t("Maximum tokens")}<input type="number" min="1" max="8192" value={Number(config.maxTokens ?? 1024)} onChange={e => patch({maxTokens:Number(e.target.value)})}/></label><label>{t("Maximum steps")}<input type="number" min="1" max="20" value={Number(config.maxSteps ?? 5)} onChange={e => patch({maxSteps:Number(e.target.value)})}/></label></>}
    {kind === "ANTHROPIC" && <fieldset className="model-tool-selection"><legend>{t("Available model tools")}</legend>
      <label className="review-confirm"><input type="checkbox" checked={Array.isArray(config.toolActorIds)} onChange={e => {const next={...config}; if(e.target.checked) next.toolActorIds=[]; else delete next.toolActorIds; update({annotations:{...node.annotations,"interlock.runtime":next}});}}/>{t("Choose tools explicitly")}</label>
      <p className="field-help">{t("By default each task exposes its primary target tool. An explicit selection exposes 1–20 configured tools, with one call per model turn. Every tool needs a REL-05 policy from this agent permitting its purpose and data classes. Model data classes must cover all selected tools and dependency outputs. Model tasks require maximum attempts 1.")}</p>
      {Array.isArray(config.toolActorIds) && <>{nodes.filter(candidate => candidate.type === "TOOL" && ["JSON_TRANSFORM","HTTP_JSON"].includes(String((candidate.annotations?.["interlock.runtime"] as Record<string,unknown> | undefined)?.kind))).map(tool => <label className="review-confirm" key={tool.id}><input type="checkbox" checked={(config.toolActorIds as string[]).includes(tool.id)} disabled={!(config.toolActorIds as string[]).includes(tool.id) && (config.toolActorIds as string[]).length >= 20} onChange={e => patch({toolActorIds:e.target.checked ? [...config.toolActorIds as string[],tool.id] : (config.toolActorIds as string[]).filter(id => id !== tool.id)})}/>{tool.label || tool.id} <code>{tool.id}</code></label>)}
        {(config.toolActorIds as string[]).filter(id => !nodes.some(tool => tool.id === id && tool.type === "TOOL" && ["JSON_TRANSFORM","HTTP_JSON"].includes(String((tool.annotations?.["interlock.runtime"] as Record<string,unknown> | undefined)?.kind)))).map(id => <label className="review-confirm" key={id}><input type="checkbox" checked onChange={()=>patch({toolActorIds:(config.toolActorIds as string[]).filter(item=>item!==id)})}/>{id} · {t("unavailable; deselect or configure this tool")}</label>)}
        {config.toolActorIds.length === 0 && <p role="alert">{t("Select at least one configured tool, or turn off explicit selection to use each task’s primary target.")}</p>}</>}
    </fieldset>}
    {(kind === "HTTP_JSON" || kind === "JSON_TRANSFORM") && <details><summary>{t("Advanced argument mapping")}</summary><p className="field-help">{t("Without a mapping, this tool receives input.tasks[task-id]. A mapping replaces those arguments.")}</p>{config.arguments !== undefined && <button className="secondary-button" onClick={()=>{const next={...config};delete next.arguments;update({annotations:{...node.annotations,"interlock.runtime":next}});}}>{t("Remove argument mapping")}</button>}<JsonEditor key={`${node.id}-${kind}-arguments-${config.arguments !== undefined}`} label={t("Arguments · {$path: input.message} or dependencies.task-id.field")} value={config.arguments} onChange={args => patch({arguments:args})}/></details>}</>}
    <SchemaEditor key={`${node.id}-input`} label={t("Input schema")} value={node.inputSchema} onChange={inputSchema => update({inputSchema})}/><SchemaEditor key={`${node.id}-output`} label={t("Output schema")} value={node.outputSchema} onChange={outputSchema => update({outputSchema})}/>
  </section>;
}
function SchemaEditor({label,value,onChange}: {label:string; value:Record<string,unknown> | undefined; onChange:(v:Record<string,unknown>)=>void}) {
  const { t } = useLanguage();
  const [name,setName] = useState(""); const [type,setType] = useState("string"); const [revision,setRevision] = useState(0);
  const properties = (value?.properties ?? {}) as Record<string,unknown>;
  return <details><summary>{t(label)}</summary><p className="field-help">{t("Object fields:")} {Object.keys(properties).join(", ") || t("none")}</p><label>{t("New field name")}<input value={name} onChange={e=>setName(e.target.value)}/></label><label>{t("Field type")}<select value={type} onChange={e=>setType(e.target.value)}>{["string","number","integer","boolean","object","array"].map(t=><option key={t}>{t}</option>)}</select></label><button className="secondary-button" disabled={!name.trim()} onClick={()=>{onChange({...value,type:"object",properties:{...properties,[name.trim()]:{type}},required:[...new Set([...(value?.required as string[] ?? []),name.trim()])]});setName("");setRevision(v=>v+1);}}>{t("Add required field")}</button><JsonEditor key={revision} label={t("Advanced schema JSON")} value={value} onChange={onChange}/></details>;
}
export function InputFields({schema,text,onChange,prefix=""}: {schema:Record<string,unknown> | undefined;text:string;onChange:(v:string)=>void;prefix?:string}) {
  const { t } = useLanguage();
  let input: Record<string,unknown>; try {input=JSON.parse(text); if (!input || typeof input !== "object" || Array.isArray(input)) return null;} catch {return null;}
  const properties=(schema?.properties ?? {}) as Record<string,Record<string,unknown>>;
  return <div className="live-controls live-control-grid">{Object.entries(properties).map(([name,s])=>s.type === "object" ? <fieldset key={name}><legend>{prefix}{name}</legend><InputFields schema={s} prefix={`${prefix}${name}.`} text={JSON.stringify(input[name] ?? {})} onChange={v=>onChange(JSON.stringify({...input,[name]:JSON.parse(v)},null,2))}/></fieldset> : ["string","number","integer","boolean"].includes(String(s.type)) ? <label key={name}>{prefix}{name}{(schema?.required as string[] ?? []).includes(name) ? " *" : ""}{s.type === "boolean" ? <select value={String(input[name] ?? "")} onChange={e=>{const next={...input};if(!e.target.value) delete next[name];else next[name]=e.target.value === "true";onChange(JSON.stringify(next,null,2));}}><option value="">{t("Choose…")}</option><option>true</option><option>false</option></select> : <input type={s.type === "string" ? "text" : "number"} step={s.type === "integer" ? "1" : "any"} value={String(input[name] ?? "")} onChange={e=>{const next={...input};if(e.target.value === "") delete next[name];else next[name]=s.type === "string" ? e.target.value : Number(e.target.value);onChange(JSON.stringify(next,null,2));}}/>}<small>{String(s.description ?? "")}</small></label> : null)}</div>;
}
export function Readiness({value}: {value: unknown}) {
  const { t } = useLanguage();
  if (!value || typeof value !== "object") return null;
  if ((value as {hostConfigured?: boolean}).hostConfigured === false) return <section className="runtime-readiness"><strong>{t("Host-managed adapters")}</strong><p>{t("This host supplies custom task adapters. Their bindings are checked when you start a run; the Studio configurable-runtime check does not apply.")}</p></section>;
  const status = value as {ready?:boolean; nodes?:Array<{actorId:string;configured:boolean;missing:boolean;problems:string[]}>;tasks?:Array<{taskId:string;sourceActorId:string;targetActorId:string;configured:boolean;problems:string[]}>; problems?:unknown};
  return <section className="runtime-readiness"><strong>{status.ready === true ? t("Ready to run") : status.ready === false ? t("Runtime setup needed") : t("Runtime preflight")}</strong><p className="field-help">{t("Credential values stay on the host. Fix missing bindings in the actor runtime form or ask the host administrator to add the named credential.")}</p>{status.nodes?.map(node=><p key={node.actorId}><b>{node.actorId}</b> · {node.problems.length ? node.problems.join("; ") : node.configured ? t("Configured") : t("No actor implementation; task adapter determines readiness")}</p>)}{status.tasks?.map(task=><p key={task.taskId}><b>{task.taskId}</b> · {task.sourceActorId} → {task.targetActorId} · {task.configured ? t("Ready") : task.problems.join("; ")}</p>)}<details><summary>{t("Full preflight diagnostics")}</summary><pre>{JSON.stringify(value,null,2)}</pre></details></section>;
}
