"""Generate a runnable project skeleton and its security tests from an Architecture manifest.

``interlock architecture skeleton <manifest> --out-dir DIR`` writes two files:

- ``<architecture>_skeleton.py`` — the project module contract every Interlock project has:
  ``MANIFEST``, ``TENANT_ID``, ``SOURCE_ACTOR_ID``, one ``ToolDefinition`` and one TODO handler per
  invoked TOOL node, ``BINDINGS``, and ``build()`` returning the gateway and the guarded tools that
  go straight into ``client.beta.messages.tool_runner``. ``examples/support_agent`` is the same
  contract written by hand, and ``interlock verify`` imports it.
- ``test_<architecture>_security.py`` — per guarded tool, a denied-data-class test whose
  expectation is asserted through the security-statistics reducer, and, when the manifest admits
  one, a declared-flow test that actually runs the tool through the guard.

**Only TOOL edges are generated.** The earlier generator wired every Actor and LinkPolicy through
the SDK's ``Interlock`` and tested each edge with ``wrap()``. A project whose runtime is the tool
runner never calls ``wrap``, so that wiring tested the framework rather than the project, and the
gateway registers only the REL-05 neighbourhood of the tools it guards (see
``mcp_transport.bind_gateway_actors``). A static non-TOOL edge is therefore named in a comment in
both generated files instead of being wired into a build the project would not use.
"""

from __future__ import annotations

import re
from collections.abc import Mapping, Sequence
from dataclasses import MISSING, dataclass, fields
from enum import Enum
from pathlib import Path
from typing import Any

from .architecture import ArchitectureEdge, ArchitectureGraph, ArchitectureNode
from .canonical import canonical_digest
from .intent import DESTINATION_FORMATS, derive_intent, side_effect_rank
from .models import ActorType, ControlDecision, SideEffect, ToolDefinition

_GENERATED_HEADER = (
    "# Generated by `interlock architecture skeleton` — edit handlers, keep wiring.\n# ruff: noqa: E501, F401\n"
)

_READ_ONLY = frozenset({SideEffect.NONE, SideEffect.READ})


def python_identifier(value: str) -> str:
    cleaned = re.sub(r"[^0-9a-zA-Z_]", "_", value).strip("_") or "unnamed"
    return f"_{cleaned}" if cleaned[0].isdigit() else cleaned


def _literal(value: object) -> str:
    if isinstance(value, Enum):
        return f"{type(value).__name__}.{value.name}"
    if isinstance(value, frozenset):
        if not value:
            return "frozenset()"
        items = sorted(value, key=lambda item: getattr(item, "value", str(item)))
        return "frozenset({" + ", ".join(_literal(item) for item in items) + "})"
    if isinstance(value, tuple):
        inner = ", ".join(_literal(item) for item in value)
        return f"({inner},)" if len(value) == 1 else f"({inner})"
    if isinstance(value, Mapping):
        return repr(dict(value))
    return repr(value)


def _dataclass_call(instance: object) -> str:
    parts = []
    for field in fields(instance):
        value = getattr(instance, field.name)
        if field.default is not MISSING and value == field.default:
            continue
        if field.default_factory is not MISSING and value == field.default_factory():
            continue
        parts.append(f"{field.name}={_literal(value)}")
    return f"{type(instance).__name__}({', '.join(parts)})"


def _blocked_data_class(edge: ArchitectureEdge, node: ArchitectureNode) -> str:
    """A data class the edge policy refuses. An explicitly denied class is the clearest one; the
    fallback is a class outside both the policy allow-list and the target Actor's grant."""
    if edge.policy.denied_data_classes:
        return sorted(edge.policy.denied_data_classes)[0]
    excluded = edge.policy.allowed_data_classes | node.actor.data_access
    return next(item for item in ("D5", "D8", "D9", "D999") if item not in excluded)


def _has_pattern(schema: Any) -> bool:
    """Whether a schema anywhere under here constrains a string with ``pattern``, which no sample
    argument can be generated for."""
    if not isinstance(schema, Mapping):
        return False
    if "pattern" in schema:
        return True
    properties = schema.get("properties")
    values = list(properties.values()) if isinstance(properties, Mapping) else []
    if schema.get("items") is not None:
        values.append(schema["items"])
    return any(_has_pattern(item) for item in values)


def _marks_destination(schema: Mapping[str, Any]) -> bool:
    return schema.get("format") in DESTINATION_FORMATS or schema.get("x-interlock-destination") is True


def _sample(schema: Any, domain: str) -> Any:
    """The smallest instance of ``schema`` that ``security.validate_schema`` accepts.

    Only the required properties are filled in: ``additionalProperties: false`` is common and a
    property nobody required is a property nobody needs a sample of. A destination property is
    filled from the target Actor's own allow-list so the generated call is one the M9 controls
    admit rather than one they hold.
    """
    if not isinstance(schema, Mapping) or not schema:
        return {}
    if schema.get("enum"):
        return schema["enum"][0]
    kind = schema.get("type")
    if kind == "object":
        properties = schema.get("properties") if isinstance(schema.get("properties"), Mapping) else {}
        return {name: _sample(properties.get(name, {}), domain) for name in schema.get("required", ())}
    if kind == "array":
        return []
    if kind in {"integer", "number"}:
        return 1
    if kind == "boolean":
        return True
    if kind == "string":
        if _marks_destination(schema):
            if schema.get("format") == "email":
                return f"sample@{domain}"
            return domain if schema.get("format") == "hostname" else f"https://{domain}/"
        value = "sample"
        max_length = schema.get("maxLength")
        return value[:max_length] if isinstance(max_length, int) else value
    return {}


@dataclass(frozen=True, slots=True)
class _Wiring:
    """One TOOL node the source Actor invokes, and everything both generators need about it."""

    node: ArchitectureNode
    edge: ArchitectureEdge
    constant: str
    definition: ToolDefinition
    purpose: str
    sample_input: Mapping[str, Any]
    sample_output: Any
    refused_by: tuple[str | None, str] | None

    @property
    def handler(self) -> str:
        """The generated handler function's name, which is also the tool's name to the model."""
        return self.definition.tool_name


def _effective_side_effect(node: ArchitectureNode, read_only: bool) -> SideEffect:
    """What the guarded tool will declare: the annotation's assertion, or the strongest effect the
    Actor is allowed to have when the annotations assert nothing (``adapters.anthropic_tools``)."""
    if read_only:
        return SideEffect.READ
    if not node.actor.side_effects:
        return SideEffect.NONE
    return max(node.actor.side_effects, key=side_effect_rank)


def _refusal(
    wiring_node: ArchitectureNode, edge: ArchitectureEdge, definition: ToolDefinition, sample: Any
) -> tuple[str | None, str] | None:
    """The control that would refuse a declared call on this tool, and why, or None.

    The generator knows the definition it is emitting and the policy that will judge it, so it can
    assert the refusal rather than emitting a declared-flow test that fails with it. A ``None``
    code means no call can be generated at all, so there is nothing to assert either way.
    """
    actor = wiring_node.actor
    policy = edge.policy
    if actor.definition_digest and actor.definition_digest != canonical_digest(definition.canonical_value()):
        return "L1-M2-DEFINITION-DRIFT", "the manifest pins a digest this definition does not have"
    if _has_pattern(definition.input_schema) or _has_pattern(definition.output_schema):
        return None, "the schema constrains a string with `pattern`, so no sample argument can be generated"
    effect = _effective_side_effect(wiring_node, definition.annotations.get("readOnlyHint") is True)
    if effect == SideEffect.EXTERNAL_WRITE and policy.external_write_requires_approval:
        return (
            "INTERLOCK-APPROVAL-REQUIRED",
            "a guarded tool declares no approval id, so this edge needs `externalWriteRequiresApproval: false` "
            "or a human gate in front of the run",
        )
    if effect == SideEffect.DESTRUCTIVE_WRITE and policy.destructive_write_action != ControlDecision.ALLOW:
        return "INTERLOCK-DESTRUCTIVE-WRITE", "the policy refuses a destructive write on this edge"
    marked = derive_intent({}, definition.input_schema, {}).derivable
    if marked and not actor.allowed_domains:
        return "L1-M9-NEW-DESTINATION", "the input schema names a destination and the Tool has no allowedDomains"
    if effect == SideEffect.EXTERNAL_WRITE and policy.require_explicit_destination and not marked:
        return "L1-M9-NEW-DESTINATION", "an external write whose input schema marks no destination"
    if derive_intent(sample, definition.input_schema, {}).destinations and not actor.allowed_domains:
        return "L1-M9-NEW-DESTINATION", "the sample call names a destination the Tool does not allow"
    return None


def _source_actor_id(graph: ArchitectureGraph, edges: Sequence[ArchitectureEdge]) -> str:
    """The Actor whose tools these are: the source of the first INVOKES edge, which is the one
    Actor ``guard_tools`` binds every tool to."""
    if edges:
        return edges[0].source
    agents = [node.id for node in graph.nodes if node.actor.type in {ActorType.AGENT, ActorType.SUBAGENT}]
    return agents[0] if agents else ""


def _wirings(graph: ArchitectureGraph) -> tuple[str, tuple[_Wiring, ...]]:
    nodes = {node.id: node for node in graph.nodes}
    invokes = [
        edge
        for edge in graph.edges
        if not edge.dynamic
        and edge.relationship_id == "REL-05"
        and edge.target in nodes
        and nodes[edge.target].actor.type == ActorType.TOOL
    ]
    source = _source_actor_id(graph, invokes)
    wirings: list[_Wiring] = []
    taken: set[str] = set()
    for edge in invokes:
        if edge.source != source or edge.target in taken:
            continue
        node = nodes[edge.target]
        short = python_identifier(edge.target.rsplit(".", 1)[-1])
        name = short if short not in taken else python_identifier(edge.target)
        taken.add(name)
        taken.add(edge.target)
        read_only = bool(node.actor.side_effects) and node.actor.side_effects <= _READ_ONLY
        definition = ToolDefinition(
            server_id=edge.target,
            tool_name=name,
            title=name.replace("_", " "),
            description=f"TODO: tell the model what {name} does and when to use it.",
            input_schema=dict(node.actor.input_schema),
            output_schema=dict(node.actor.output_schema),
            annotations={"readOnlyHint": True} if read_only else {},
        )
        domain = sorted(node.actor.allowed_domains)[0] if node.actor.allowed_domains else "example.test"
        sample_input = _sample(definition.input_schema, domain)
        wirings.append(
            _Wiring(
                node=node,
                edge=edge,
                constant=name.upper(),
                definition=definition,
                purpose=sorted(edge.policy.allowed_purposes)[0]
                if edge.policy.allowed_purposes
                else edge.relationship.lower(),
                sample_input=sample_input,
                sample_output=_sample(definition.output_schema, domain),
                refused_by=_refusal(node, edge, definition, sample_input),
            )
        )
    return source, tuple(wirings)


def _uncovered_edges(graph: ArchitectureGraph, wirings: Sequence[_Wiring]) -> list[str]:
    """Comment lines for every static edge no guarded tool covers."""
    covered = {wiring.edge.id for wiring in wirings}
    lines = []
    for edge in graph.edges:
        if edge.id in covered:
            continue
        reason = "dynamic: connect concrete targets at runtime" if edge.dynamic else "not an invoked TOOL edge"
        lines.append(f"# edge {edge.id!r} ({edge.source!r} {edge.relationship} {edge.target!r}) is {reason}")
    return lines


def generate_skeleton(graph: ArchitectureGraph, manifest_path: str | Path) -> str:
    source, wirings = _wirings(graph)
    lines = [
        _GENERATED_HEADER,
        f'"""Interlock wiring for architecture {graph.id!r} v{graph.version}.',
        "",
        "Write the handlers and the tool descriptions; keep the contract:",
        "MANIFEST, TENANT_ID, SOURCE_ACTOR_ID, BINDINGS and build() are what the tool runner,",
        '`interlock verify` and the generated security tests all read."""',
        "",
        "from __future__ import annotations",
        "",
        "import json",
        "from collections.abc import Sequence",
        "from dataclasses import replace",
        "from pathlib import Path",
        "",
        "from agent_interlock import (",
        "    ArchitectureGraph,",
        "    Ledger,",
        "    MCPToolGateway,",
        "    ToolBinding,",
        "    ToolDefinition,",
        "    bind_architecture,",
        "    guard_tools,",
        ")",
        "from agent_interlock.canonical import canonical_digest",
        "",
        f"MANIFEST = Path({str(Path(manifest_path))!r})",
        'TENANT_ID = "tenant-dev"  # TODO: your tenant',
        f"SOURCE_ACTOR_ID = {source!r}",
        'APPROVER = "TODO: the reviewer who signed off these tool definitions"',
        "",
    ]
    lines += _uncovered_edges(graph, wirings)
    for wiring in wirings:
        lines += [
            "",
            "",
            f"def {wiring.handler}(arguments):",
            f'    """TODO: implement {wiring.edge.target!r}. Runs only as the gateway\'s connector."""',
            f'    raise NotImplementedError("{wiring.handler}")',
            "",
            "",
            f"{wiring.constant} = {_dataclass_call(wiring.definition)}",
        ]
    lines += ["", "", "BINDINGS: tuple[ToolBinding, ...] = ("]
    for wiring in wirings:
        lines.append(
            f"    ToolBinding({wiring.constant}, {wiring.handler}, {wiring.edge.target!r}, {wiring.purpose!r}),"
        )
    lines += [
        ")",
        "",
        "",
        "def _pin_definitions(graph: ArchitectureGraph, bindings: Sequence[ToolBinding]) -> ArchitectureGraph:",
        '    """Give every unpinned TOOL node the digest of the definition bound to it.',
        "",
        "    A node that already carries a pin is left as authored: a pin that disagrees with the",
        '    definition is drift, and L1-M2-DEFINITION-DRIFT has to report it at call time."""',
        "    digests = {",
        "        binding.actor_id: canonical_digest(binding.definition.canonical_value()) for binding in bindings",
        "    }",
        "    nodes = tuple(",
        "        node",
        "        if node.id not in digests or node.actor.definition_digest is not None",
        "        else replace(node, actor=replace(node.actor, definition_digest=digests[node.id]))",
        "        for node in graph.nodes",
        "    )",
        "    return replace(graph, nodes=nodes)",
        "",
        "",
        "def build(bindings: Sequence[ToolBinding] = BINDINGS, *, ledger: Ledger | None = None):",
        '    """Compile the manifest and return (gateway, guarded tools) ready for the tool runner."""',
        "    graph = ArchitectureGraph.from_dict(json.loads(MANIFEST.read_text(encoding='utf-8')))",
        "    gateway = MCPToolGateway(ledger=ledger)",
        "    bind_architecture(",
        "        gateway,",
        "        _pin_definitions(graph, bindings),",
        "        tool_bindings={binding.definition.tool_name: binding.actor_id for binding in bindings},",
        "        approver=APPROVER,",
        "    )",
        "    tools = guard_tools(",
        "        gateway,",
        "        tenant_id=TENANT_ID,",
        "        source_actor_id=SOURCE_ACTOR_ID,",
        "        bindings=list(bindings),",
        "        approver=APPROVER,",
        "    )",
        "    return gateway, tools",
        "",
    ]
    return "\n".join(lines)


def generate_security_tests(graph: ArchitectureGraph, skeleton_module: str) -> str:
    source, wirings = _wirings(graph)
    lines = [
        _GENERATED_HEADER,
        f'"""Generated security tests for architecture {graph.id!r} — verified via the statistics reducer."""',
        "",
        "import json",
        "import unittest",
        "from dataclasses import replace",
        "",
        "from agent_interlock import (",
        "    ControlDecision,",
        "    InvocationBlocked,",
        "    InvocationIntent,",
        "    SideEffect,",
        "    reduce_interactions,",
        ")",
        "",
        f"from {skeleton_module} import BINDINGS, SOURCE_ACTOR_ID, TENANT_ID, build",
        "",
        "",
        "def stubbed(index, value):",
        '    """BINDINGS with one handler replaced: the generated handlers raise until you write them."""',
        "    return tuple(",
        "        replace(binding, function=lambda arguments, result=value: result) if position == index else binding",
        "        for position, binding in enumerate(BINDINGS)",
        "    )",
        "",
        "",
        "def records_for(gateway):",
        "    return reduce_interactions([event.to_dict() for event in gateway.ledger.all()])",
        "",
    ]
    lines += _uncovered_edges(graph, wirings)
    for index, wiring in enumerate(wirings):
        class_name = f"Tool_{python_identifier(wiring.edge.target)}_Tests"
        lines += [
            "",
            "",
            f"class {class_name}(unittest.TestCase):",
        ]
        if wiring.refused_by is None:
            lines += [
                "    def test_declared_flow_is_allowed(self):",
                f"        gateway, tools = build(stubbed({index}, {wiring.sample_output!r}))",
                f"        result = tools[{index}].call({dict(wiring.sample_input)!r})",
                f"        self.assertEqual(json.loads(result), {wiring.sample_output!r})",
                "        records = records_for(gateway)",
                "        self.assertTrue(records and not records[-1].block_decision)",
                "        self.assertTrue(records[-1].execution_succeeded)",
                "",
            ]
        blocked = _blocked_data_class(wiring.edge, wiring.node)
        enforced = wiring.edge.policy.mode.value == "ENFORCE"
        if wiring.refused_by is not None:
            code, explanation = wiring.refused_by
            if code is None or not enforced:
                lines += [f"    # No declared-flow test: {explanation}.", ""]
            else:
                lines += [
                    "    def test_declared_flow_is_refused_by_the_manifest(self):",
                    f'        """As written, {explanation}. Fix the manifest or the definition, then',
                    '        regenerate: this test is the generator\'s reading of what the policy admits."""',
                    f"        gateway, tools = build(stubbed({index}, {wiring.sample_output!r}))",
                    "        with self.assertRaises(Exception) as raised:  # anthropic ToolError, or its stand-in",
                    f"            tools[{index}].call({dict(wiring.sample_input)!r})",
                    f"        self.assertIn({code!r}, str(raised.exception))",
                    "        self.assertTrue(any(record.enforced_block for record in records_for(gateway)))",
                    "",
                ]
        lines += [
            "    def test_undeclared_data_class_is_blocked(self):",
            "        gateway, tools = build()",
            "        decision = gateway.evaluate_invocation(",
            "            tenant_id=TENANT_ID,",
            "            source_actor_id=SOURCE_ACTOR_ID,",
            f"            revision_id=tools[{index}].revision.revision_id,",
            "            intent=InvocationIntent(",
            f"                purpose={wiring.purpose!r},",
            f"                data_classes=frozenset({{{blocked!r}}}),",
            "                estimated_side_effect=SideEffect.NONE,",
            "            ),",
            f"            arguments={dict(wiring.sample_input)!r},",
            "        )",
            "        self.assertNotEqual(decision.decision, ControlDecision.ALLOW)",
            "        self.assertTrue(decision.reason_codes)",
            "        # The verdict alone is not the evidence the reducer counts: the enforcement action and",
            "        # the security outcome are recorded when the decision is carried out.",
        ]
        run_call = (
            f"        gateway.execute_approved_call(decision.decision_id, {dict(wiring.sample_input)!r}, "
            f"lambda arguments: {wiring.sample_output!r}, idempotency_key='denied-data-class')"
        )
        if enforced:
            lines += [
                "        with self.assertRaises(InvocationBlocked):",
                f"    {run_call}",
                "        self.assertTrue(any(record.enforced_block for record in records_for(gateway)))",
            ]
        else:
            lines += [
                run_call,
                "        self.assertTrue(any(record.shadow_would_block for record in records_for(gateway)))",
            ]
        lines.append("")
    lines += ["", 'if __name__ == "__main__":', "    unittest.main()", ""]
    return "\n".join(lines)
