"""Generate SDK skeleton and security-test modules from an Architecture manifest.

``interlock architecture skeleton <manifest> --out-dir DIR`` writes two files:

- ``<architecture>_skeleton.py`` — ``build()`` wiring every declared Actor and
  LinkPolicy through the SDK, plus one TODO handler stub per invoked target.
  The user's real feature code replaces the stubs; the contract wiring stays.
- ``test_<architecture>_security.py`` — per static edge, one allowed-flow test
  and one denied-data-class test whose expectations are asserted through the
  security-statistics reducer, so generated tests and the analytics contract
  agree on what "blocked" means.
"""

from __future__ import annotations

import re
from collections.abc import Mapping
from dataclasses import MISSING, fields
from enum import Enum

from .architecture import ArchitectureGraph

_GENERATED_HEADER = (
    "# Generated by `interlock architecture skeleton` — edit handlers, keep wiring.\n# ruff: noqa: E501, F401\n"
)


def python_identifier(value: str) -> str:
    cleaned = re.sub(r"[^0-9a-zA-Z_]", "_", value).strip("_") or "unnamed"
    return f"_{cleaned}" if cleaned[0].isdigit() else cleaned


def _literal(value: object) -> str:
    if isinstance(value, Enum):
        return f"{type(value).__name__}.{value.name}"
    if isinstance(value, frozenset):
        if not value:
            return "frozenset()"
        items = sorted(value, key=lambda item: getattr(item, "value", str(item)))
        return "frozenset({" + ", ".join(_literal(item) for item in items) + "})"
    if isinstance(value, tuple):
        inner = ", ".join(_literal(item) for item in value)
        return f"({inner},)" if len(value) == 1 else f"({inner})"
    if isinstance(value, Mapping):
        return repr(dict(value))
    return repr(value)


def _dataclass_call(instance: object) -> str:
    parts = []
    for field in fields(instance):
        value = getattr(instance, field.name)
        if field.default is not MISSING and value == field.default:
            continue
        if field.default_factory is not MISSING and value == field.default_factory():
            continue
        parts.append(f"{field.name}={_literal(value)}")
    return f"{type(instance).__name__}({', '.join(parts)})"


def _blocked_data_class(access: frozenset[str]) -> str:
    return next(item for item in ("D5", "D8", "D9", "D999") if item not in access)


def generate_skeleton(graph: ArchitectureGraph) -> str:
    lines = [
        _GENERATED_HEADER,
        f'"""SDK wiring for architecture {graph.id!r} v{graph.version}."""',
        "",
        "from agent_interlock import (",
        "    ActorSpec,",
        "    ActorType,",
        "    ControlDecision,",
        "    FailureMode,",
        "    Interlock,",
        "    LinkPolicy,",
        "    PolicyMode,",
        "    SideEffect,",
        ")",
        "",
        'TENANT_ID = "tenant-dev"  # TODO: your tenant',
        "",
        "",
        "def build():",
        '    """Wire every declared Actor and LinkPolicy; returns (interlock, actors)."""',
        "    interlock = Interlock()",
        "    actors = {}",
    ]
    for node in graph.nodes:
        lines.append(f"    actors[{node.id!r}] = interlock.define_actor({_dataclass_call(node.actor)})")
    for edge in graph.edges:
        if edge.dynamic:
            lines.append(f"    # dynamic edge {edge.id!r} targets a selector; connect concrete actors at runtime")
            continue
        lines.append(f"    actors[{edge.source!r}].connect(actors[{edge.target!r}], {_dataclass_call(edge.policy)})")
    lines.append("    return interlock, actors")
    lines.append("")

    seen_targets: list[str] = []
    for edge in graph.edges:
        if edge.dynamic or edge.target in seen_targets:
            continue
        seen_targets.append(edge.target)
        handler = f"handle_{python_identifier(edge.target)}"
        lines += [
            "",
            f"def {handler}(arguments):",
            f'    """TODO: implement target {edge.target!r} ({edge.relationship} from {edge.source!r})."""',
            f'    raise NotImplementedError("{handler}")',
        ]
    lines += ["", "", "HANDLERS = {"]
    for edge in graph.edges:
        if edge.dynamic:
            continue
        lines.append(f"    {edge.id!r}: handle_{python_identifier(edge.target)},")
    lines += ["}", ""]
    return "\n".join(lines)


def generate_security_tests(graph: ArchitectureGraph, skeleton_module: str) -> str:
    nodes = {node.id: node.actor for node in graph.nodes}
    lines = [
        _GENERATED_HEADER,
        f'"""Generated security tests for architecture {graph.id!r} — verified via the statistics reducer."""',
        "",
        "import unittest",
        "",
        "from agent_interlock import GatewayError, InvocationIntent, reduce_interactions",
        "",
        f"from {skeleton_module} import TENANT_ID, build",
        "",
    ]
    for edge in graph.edges:
        if edge.dynamic:
            lines.append(f"# dynamic edge {edge.id!r}: write targeted tests once concrete targets exist")
            continue
        target = nodes[edge.target]
        class_name = f"Edge_{python_identifier(edge.id)}_Tests"
        allowed_classes = sorted(target.data_access)[:1]
        allowed = (
            "frozenset({" + ", ".join(repr(item) for item in allowed_classes) + "})"
            if allowed_classes
            else "frozenset()"
        )
        blocked = _blocked_data_class(target.data_access)
        purpose = sorted(edge.policy.allowed_purposes)[0] if edge.policy.allowed_purposes else edge.relationship.lower()
        enforced = edge.policy.mode.value == "ENFORCE"
        lines += [
            "",
            f"class {class_name}(unittest.TestCase):",
            "    def test_declared_flow_is_allowed(self):",
            "        interlock, actors = build()",
            f"        guarded = actors[{edge.target!r}].wrap(lambda arguments: {{'ok': True}})",
            "        result = guarded(",
            "            {},",
            f"            source=actors[{edge.source!r}],",
            "            tenant_id=TENANT_ID,",
            f"            intent=InvocationIntent(purpose={purpose!r}, data_classes={allowed}),",
            "        )",
            "        self.assertEqual(result, {'ok': True})",
            "        records = reduce_interactions(event.to_dict() for event in interlock.ledger.all())",
            "        self.assertTrue(records and not records[-1].block_decision)",
            "",
            "    def test_undeclared_data_class_is_blocked(self):",
            "        interlock, actors = build()",
            f"        guarded = actors[{edge.target!r}].wrap(lambda arguments: {{'ok': True}})",
            f"        intent = InvocationIntent(purpose={purpose!r}, data_classes=frozenset({{{blocked!r}}}))",
        ]
        if enforced:
            lines += [
                "        with self.assertRaises(GatewayError):",
                f"            guarded({{}}, source=actors[{edge.source!r}], tenant_id=TENANT_ID, intent=intent)",
                "        records = reduce_interactions(event.to_dict() for event in interlock.ledger.all())",
                "        self.assertTrue(any(record.enforced_block for record in records))",
            ]
        else:
            lines += [
                f"        guarded({{}}, source=actors[{edge.source!r}], tenant_id=TENANT_ID, intent=intent)",
                "        records = reduce_interactions(event.to_dict() for event in interlock.ledger.all())",
                "        self.assertTrue(any(record.shadow_would_block for record in records))",
            ]
        lines.append("")
    lines += ["", 'if __name__ == "__main__":', "    unittest.main()", ""]
    return "\n".join(lines)
